### ISSUE TITLE
Weight Axis variable font

### ISSUE THREAD

**Issue by pichotta** [EbenSorkin/Merriweather-Sans#14]
Hello @EbenSorkin ,

As you know the Google fonts team would love to see a variable font version of ‘Merriweather-Sans'. They have commissioned us @TypeNetwork to work on upgrading a number of font families to be variable fonts with a single weight axis.

We can see from the notes on this repo that an upgrade for the 'Merriweather-Sans' family is in progress on this new git repo.  https://github.com/SorkinType/Merriweather-Sans

To assess how we might be able to assist in this effort would you be able to outline the changes between these two git repos?  The version at 'EbenSorkin/' vs. the version at 'SorkinType/'?  What are the major differences?  Is there planned backwards compatibility with the static instances in terms of weights and horizontal and vertical metrics?

Thank for any information. We look forward to working with you and Google fonts to determine the next best steps.

Best Regards,

Jill Pichotta
Vice President
Type Network
pichotta@typenetwork.com

**Comment by EbenSorkin** [comment]
I think the main issues should be glyphs source to  fontmake related. I did all but one technical thing with this source. I think the sorkintype git notes day what. Shall we chat on Tuesday?

**Comment by pichotta** [comment]
https://github.com/google/fonts/pull/2632
