### ISSUE TITLE
Naming inconsistencies

### ISSUE THREAD

**Issue by charakterziffer** [EbenSorkin/Merriweather-Sans#15]
Some times ago the boldest weight of Merriweather was called ExtraBold rsp. ExtraBold-Italic. Now it’s Black and UltraBold-Italic. Is there a reason not to be consequent with

- ExtraBold / ExtraBold-Italic
- UltraBold / UltraBold-Italic
- or Black / Black-Italic?

**Comment by EbenSorkin** [comment]
Where are you seeing ultra bold-italic now? From a download or the google webfont service?

**Comment by charakterziffer** [comment]
Sorry, for not being specific enough. I’ve downloaded the static ttf fonts from this repository: https://github.com/EbenSorkin/Merriweather-Sans/tree/master/fonts/ttfs – but also on https://github.com/SorkinType/Merriweather-Sans/tree/master/fonts/ttfs there’s an Ultrabold-Italic.

(I prefer not to download fonts from Google but assume they are more up-to-date on their source page)

**Comment by EbenSorkin** [comment]
This repository is being re-worked on now ( not by me ) and there should be an update this year. I'll see what I can discover about the current status of this is and what they plan to do with style names.

Is this a general question about approach or it the case that you have a problem such as document that doesn't look right without the missing font?

-e.

**Comment by charakterziffer** [comment]
Not a great problem, just a little puzzling in the font menu of the writer software. First I thought the style linking is broken because of this name inconsistency but I’ve seen that Merriweather generally has no style linking (clicking the italic button gives fake oblique instead the designed true italic).

I installed the fonts from Google now where the style linking works. Thank you!

**Comment by EbenSorkin** [comment]
Most welcome.

-e.
