### ISSUE TITLE
Fix superiors in all styles

### ISSUE THREAD

**Issue by davelab6** [EbenSorkin/Merriweather-Sans#5]
The `onesuperior` `twosuperior` and `threesuperior` glyphs are not in all styles:
- [x] MerriweatherSans-Regular.ufo
- [ ] MerriweatherSans-Italic.ufo
- [x] MerriweatherSans-Bold.ufo
- [x] MerriweatherSans-BoldItalic.ufo
- [ ] MerriweatherSans-ExtraBold.ufo
- [ ] MerriweatherSans-ExtraBoldItalic.ufo
- [ ] MerriweatherSans-Light.ufo
- [ ] MerriweatherSans-LightItalic.ufo

Since these have to be drawn, I haven't fixed them myself.

**Comment by davelab6** [comment]
There are clearly other differences I didn't look into as the regular has more glyphs than any other style, 481.

**Comment by EbenSorkin** [comment]
This is fixed now.

See: 

https://github.com/SorkinType/Merriweather-Sans/commit/2b53cbf652f34b70c38aad6a184b0f371f4ce3af
