### ISSUE TITLE
Lining numbers

### ISSUE THREAD

**Issue by AmiciA** [EbenSorkin/Merriweather-Sans#8]
Is it possible to add lining numbers (proportional or tabular) to Merriweather Sans?

**Comment by EbenSorkin** [comment]
It is. I hope I'll get to do that this year.

-e.

**Comment by AmiciA** [comment]
Cool, looking forward to it! And thanks for the quick reply!

**Comment by JuneWhitmore** [comment]
I'd also very much like to hear about tabular numbers in Merriweather Sans. If done, will it just work with css like "font-variant-numeric:tabular-nums;"?

**Comment by EbenSorkin** [comment]
This has been added. See:

https://github.com/SorkinType/Merriweather-Sans
https://github.com/SorkinType/Merriweather-Sans/commit/2b53cbf652f34b70c38aad6a184b0f371f4ce3af

**Comment by j-f1** [comment]
Why the fork @EbenSorkin?

**Comment by EbenSorkin** [comment]
All the google font projects will eventually need to be moved from my
personal Git to the one of the company Sorkin Type. Google requested the
change.

There are also updates rolling in for Merriweather Sans and Merriweather.

Both regular fonts (TTF & OTF) and Variable versions are being offered.

The new fonts also come with kerning, multiple styles of numbers and small
caps and design quality improvements.

I will be updating the read me files in both repos to make this clear
shortly.

I hope this is helpful. If you have other questions let me know.

Best!

-e.

**Comment by j-f1** [comment]
Thanks for getting back to me! When I’ve seen this happen in the past, the original repo is usually transferred to the organization. As long as you don’t fork it back to your account, all links will redirect to the new repo and you won’t have to worry about having multiple copies.
